<?php 
	$hint = htmlspecialchars(trim($this->getField()->getHint())); 
	$hintClass='webforms-fields-hint';
	if ($this->getFieldValue()){
		$hint = false;
		$hintClass="";
	}
	if ($hint){
		$value= $hint;
	}else{
		$value= htmlspecialchars($this->getFieldValue());
	}
	$html = "";
	if ($this->getField()->getType() == 'email'){
		$html += ' onkeyup="if(this.value.search(\' \')>=0){this.value = this.value.replace(\' \',\'\');}"';
	}
	
	if ($this->getField()->getDisabled()) {
		$html += ' disabled';
	}
	if ($hint){
		$html += ' onfocus="if (this.value == \''. str_replace("'","\'",$hint) .'\') {this.value = \'\'; $(this).removeClassName(\'webforms-fields-hint\');}" onblur="if (this.value == \'\') {this.value = \''. str_replace("'","\'",$hint) .'\'; $(this).addClassName(\'webforms-fields-hint\');}"';
	}
	
	echo "<input type='text' name='{$this->getFieldName()}' id='{$this->getFieldId()}' class='{$this->getFieldClass()} {$hintClass}' style='{$this->getFieldStyle()}' value='{$value}' {$html} />";
?>


<!--<input type='text' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>' class='<?php echo $this->getFieldClass() ?> <?php if($hint){ echo 'webforms-fields-hint';}?>' style='<?php echo $this->getFieldStyle() ?>' value="<?php if ($hint) echo $hint; else echo htmlspecialchars($this->getFieldValue()); ?>" <?php if ($this->getField()->getType() == 'email'){ ?>onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"<?php } ?> <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?> <?php if ($hint){ ?>onfocus="if (this.value == '<?php echo str_replace("'","\'",$hint) ?>') {this.value = ''; $(this).removeClassName('webforms-fields-hint');}" onblur="if (this.value == '') {this.value = '<?php echo str_replace("'","\'",$hint) ?>'; $(this).addClassName('webforms-fields-hint');}"<?php } ?>/>-->